language: node_js

sudo: false

node_js:
  - '10'

script:
  - yarn run typecheck
  - yarn run tslint
  - yarn run prettier:check
  - yarn run cover
  - nyc report --reporter json
  - 'bash <(curl -s https://codecov.io/bash)'
